# Supabase Helm Values
# Using latest stable PostgreSQL 17.4 with Supabase extensions
# Secrets are managed separately via Kubernetes secrets

# Database Configuration
db:
  enabled: true
  image:
    repository: supabase/postgres
    tag: "17.4.1.068"  # Latest stable release
    pullPolicy: IfNotPresent

  # Resource limits for stability
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  # Persistence for data durability
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""  # Use default storage class

# Studio Configuration
studio:
  enabled: true
  image:
    repository: supabase/studio
    tag: "latest"
    pullPolicy: IfNotPresent

# Auth Service
auth:
  enabled: true
  image:
    repository: supabase/gotrue
    tag: "latest"
    pullPolicy: IfNotPresent

# REST API
rest:
  enabled: true
  image:
    repository: postgrest/postgrest
    tag: "latest"
    pullPolicy: IfNotPresent

# Realtime Service
realtime:
  enabled: true
  image:
    repository: supabase/realtime
    tag: "latest"
    pullPolicy: IfNotPresent

# Storage Service
storage:
  enabled: true
  image:
    repository: supabase/storage-api
    tag: "latest"
    pullPolicy: IfNotPresent

# Image Proxy
imgproxy:
  enabled: true
  image:
    repository: darthsim/imgproxy
    tag: "latest"
    pullPolicy: IfNotPresent

# Kong Gateway - DISABLED (using Traefik instead)
kong:
  enabled: false

# Analytics - DISABLED (optional for development)
analytics:
  enabled: false

# Vector/Telemetry - DISABLED (optional for development)  
vector:
  enabled: false

# Edge Functions - DISABLED (optional for development)
functions:
  enabled: false

# Meta API
meta:
  enabled: true
  image:
    repository: supabase/postgres-meta
    tag: "latest"
    pullPolicy: IfNotPresent
