# Simplified values for full Supabase deployment
secret:
  jwt:
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
    serviceKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
    secret: "abcdefghijklmnopqrstuvwxyz123456"
  db:
    username: "postgres"
    password: "postgres"
    database: "postgres"

# Enable all core services
db:
  enabled: true

studio:
  enabled: true

auth:
  enabled: true

rest:
  enabled: true

realtime:
  enabled: true

meta:
  enabled: true

storage:
  enabled: true

imgproxy:
  enabled: true

kong:
  enabled: true

# Disable optional services that might cause issues
analytics:
  enabled: false

vector:
  enabled: false

functions:
  enabled: false

minio:
  enabled: false
