apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase-simple
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SPRIME01/HomeStation-Core.git
    targetRevision: HEAD
    path: infra/supabase
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
